config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show]

  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'angular-items', to: 'portfolios#angular', as: 'angular_items_show'

  get 'about', to: "pages#about"
  get 'contact', to: "pages#contact"

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: "pages#home"
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
	has_many :technologies
	accepts_nested_attributes_for :technologies,
																reject_if: lambda { |attrs| attrs['name'].blank? }
	include Placeholder
	validates_presence_of :title, :subtitle, :body, :main_image, :thumb_image

	def self.angular
		where(subtitle: "Angular")
	end

	scope :ruby_on_rails_portfolio_items, -> {where(subtitle: "Ruby on Rails")}

	after_initialize :set_defaults

	def set_defaults
		self.main_image ||= Placeholder.image_generator(width:'600', height:'400')
		self.thumb_image ||= Placeholder.image_generator(width:'350', height:'200')
	end

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]
  layout "portfolio"

  def index
    @portfolio_items = Portfolio.all
  end

  def angular
    @angular_portfolio_items = Portfolio.angular
  end

  def new
    @portfolio_item = Portfolio.new
    3.times { @portfolio_item.technologies.build }
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_item_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'portfolio item was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    3.times { @portfolio_item.technologies.build }
  end

  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_item_params)
        format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
  end

  def destroy
    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_portfolio
      @portfolio_item = Portfolio.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def portfolio_item_params
    params.require(:portfolio).permit(:title, :subtitle, :body, :main_image, :thumb_image, technologies: [:name]
      )
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <ul>
    <%= form.fields_for :technologies do |technology_form| %>
      <li>
        <%= technology_form.label :name %>
        <%= technology_form.text_field :name %>
      </li>
    <% end %>
  </ul>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
  <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id) %></p>
  <p><%= portfolio_item.subtitle %></p>
  <p><%= portfolio_item.body %></p>
  <!-- <p><%= portfolio_item.main_image %></p> -->
  <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil?%>
  <%= link_to "Edit", edit_portfolio_path(portfolio_item.id) %>
  <%= link_to 'Delete portfolio item', portfolio_item, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/portfolios/angular.html.erb
<h1>Angular portfolio items</h1>

<%=link_to "Create new item", new_portfolio_path  %>

<% @angular_portfolio_items.each do |portfolio_item|%>
  <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id) %></p>
  <p><%= portfolio_item.subtitle %></p>
  <p><%= portfolio_item.body %></p>
  <!-- <p><%= portfolio_item.main_image %></p> -->
  <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil?%>
  <%= link_to "Edit", edit_portfolio_path(portfolio_item.id) %>
  <%= link_to 'Delete portfolio item', portfolio_item, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/portfolios/edit.html.erb
<h1>Edit this portfolio item</h1>
<%= render 'form', portfolio_item: @portfolio_item %>

app/views/portfolios/index.html.erb
<h1>Portfolio items</h1>

<%=link_to "Create new item", new_portfolio_path  %>

<%= render partial: "portfolio_item", collection: @portfolio_items %>

app/views/portfolios/new.html.erb
<h1>Create new portfolio item</h1>
<%= render 'form', portfolio_item: @portfolio_item %>

app/views/portfolios/show.html.erb
<%= image_tag @portfolio_item.main_image %>
<h1><%= @portfolio_item.title %></h1>
<em><%= @portfolio_item.subtitle %></em>
<p><%= @portfolio_item.body %></p>
<h2>Used technologies:</h2>
<% @portfolio_item.technologies.each do |item| %>
	<p><%= item.name %></p>
<% end %>
<p><%= link_to "Powrót", portfolios_path %></p>